<main class="main-administrar">
    <p id="estado-form">Agregar Producto</p>
    <form action="agregarProducto" method="POST" class="form-administrar">
        <div id="select-ids" class="noMostrar">
            <select>
                <?php foreach ($products as $product) : ?>
                    <option name="Product_id" value="<?= $product->Product_id ?>"><?= $product->Product_id ?></option>
                <?php endforeach ?>
            </select>
        </div>

        <div class="">
            <div class="form-group">
                <label>Nombre del producto</label>
                <input required name="Product_name" type="text" class="form-control">
            </div>
        </div>

        <div class="form-group">
            <label>Mililitros</label>
            <input type="number" name="Milliliters" class="form-control"></input>
        </div>

        <div class="form-group">
            <label>precio</label>
            <input type="number" name="price" class="form-control"></input>
        </div>

        <div class="form-group">
            <label>Categoria</label>
            <select required name="Category_id" class="form-control">
                <option value="1">1</option>
                <option value="2">2</option>
                <option value="3">3</option>
                <option value="4">4</option>
                <option value="5">5</option>
                <option value="6">6</option>
            </select>
        </div>

        <div>
            <input type="button" id="btn-form-administrar" value="Editar">
        </div>

        <button type="submit" class="btn btn-primary mt-2">Guardar</button>
    </form>


    <table>
        <thead>
            <tr>
                <th>Id</th>
                <th>Producto</th>
                <th>Mililitros</th>
                <th>Precio</th>
                <th>Categoria</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($products as $product) : ?>
                <tr>
                    <td><?= $product->Product_id ?></td>
                    <td><?= $product->Product_name ?></td>
                    <td><?= $product->Milliliters ?>ml</td>
                    <td>$<?= $product->Price ?></td>
                    <td><?= $product->Category_id ?></td>
                    <td><a href="eliminar-<?= $product->Product_id ?>" type="button">Borrar</a></td>
                </tr>
            <?php endforeach ?>
        </tbody>
    </table>
</main>

<script src="js/main.js"></script>
</body>

</html>