<main class="main-administrar">
    <div class="administrar-info">
        <div class="logo-info">
            <i class="fa-solid fa-info fa-sm"></i>
        </div>
        <p>Al apretar en el boton blanco del formulario de abajo se va a cambiar la función de este, va a pasar de permitirle al usuario agregar un producto a la base de datos, a editar uno de estos llamandolo por su id de producto (después de realizar esta accion el boton blanco va a permitirle volver al formulario anterior).<br>Aclaración: consultar la tabla del final de la pagina para saber el id del producto que desea editar.</p>
    </div>
    <form action="agregarProducto" method="POST" class="form" id="form-productos">
        <div class="form-type">
            <div class="form-input__container">
                <input class="btns-admin" type="button" value="Editar" number="1">
            </div>
            <div class="form-input__container">
                <input class="btns-admin" type="button" value="Agregar" number="2">
            </div>
            <div class="form-input__container">
                <input class="btns-admin" type="button" value="Eliminar" number="3">
            </div>
        </div>
        <p class="form-title" id="form-title-productos">Agregar Producto</p>

        <div class="noMostrar" id="select-ids-productos">
            <label for="id">Seleccione un producto</label>
            <select name="id">
                <?php foreach ($products as $product) : ?>
                    <option name="Product_id" value="<?= $product->Product_id ?>"><?= $product->Product_id ?></option>
                <?php endforeach ?>
            </select>
        </div>

        <div class="" id="cont-form-productos">
            <div class="form-input__container">
                <label>Nombre del producto</label>
                <input required name="Product_name" type="text" class="form-control">
            </div>

            <div class="form-input__container">
                <label>Mililitros</label>
                <input type="number" name="Milliliters" class="form-control"></input>
            </div>

            <div class="form-input__container">
                <label>Precio</label>
                <input type="number" name="Price" class="form-control"></input>
            </div>

            <div class="form-select__conteiner select-width">
                <label>Categoria</label>
                <select required name="Category_id" class="form-control">
                    <?php foreach ($categorys as $category) : ?>
                        <option value="<?= $category->Category_id ?>"><?= $category->Category_name ?></option>
                    <?php endforeach ?>
                </select>
            </div>
        </div>

        <button action="administrar" type="submit" class="form-submit" id="btn-submit-productos">Enviar</button>
    </form>
    <!-- <td><a href="eliminar-<?= $product->Product_id ?>" type="button">Borrar</a></td> -->

    <form action="agregarCategoria" class="form" method="POST" id="form-categorias">
        <div class="form-type">
            <div class="form-input__container">
                <input class="btns-admin" type="button" value="Editar" number="4">
            </div>
            <div class="form-input__container">
                <input class="btns-admin" type="button" value="Agregar" number="5">
            </div>
            <div class="form-input__container">
                <input class="btns-admin" type="button" value="Eliminar" number="6">
            </div>
        </div>
        <p class="form-title" id="form-title-categorias">Agregar Categoria</p>

        <div class="noMostrar" id="select-ids-categorias">
            <label for="id">Seleccione una categoria</label>
            <select name="id">
                <?php foreach ($categorys as $category) : ?>
                    <option name="Category_id" value="<?= $category->Category_id ?>"><?= $category->Category_id ?></option>
                <?php endforeach ?>
            </select>
        </div>

        <div class="" id="cont-form-categorias">
            <div class="form-input__container">
                <label>Nombre de la categoria</label>
                <input required name="Category_name" type="text" class="form-control">
            </div>
        </div>

        <button action="administrar" type="submit" class="form-submit" id="btn-submit-categorias">Enviar</button>
    </form>
    <!-- <td><a href="eliminarC-<?= $categorys[$i]->Category_id ?>" type="button">Borrar categoria</a></td> -->

    <div class="tabla-container">
        <h3>Info de los Productos</h3>
        <p>Tabla para mostrar información y eliminar productos de la base de datos</p>
        <table>
            <thead>
                <tr>
                    <th>Id</th>
                    <th>Producto</th>
                    <th>Mililitros</th>
                    <th>Precio</th>
                    <th>Categoria</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($products as $product) : ?>
                    <tr>
                        <td><?= $product->Product_id ?></td>
                        <td><?= $product->Product_name ?></td>
                        <td><?= $product->Milliliters ?>ml</td>
                        <td>$<?= $product->Price ?></td>
                        <td>
                            <?php
                            $i = 0;
                            $var = false;
                            while ($var == false && $i < count($categorys)) {
                                if ($product->Category_id == $categorys[$i]->Category_id) {
                                    $var = true;
                                    echo "(" . $categorys[$i]->Category_id . ")" . $categorys[$i]->Category_name;
                                }
                                $i++;
                            } ?>
                        </td>
                    </tr>
                <?php endforeach ?>
            </tbody>
        </table>
    </div>
</main>
<script src="js/administrar.js"></script>
<script src="js/main.js"></script>
</body>

</html>