<main class="main-administrar">

    <div class="administrar-info">
        <div class="logo-info">
            <i class="fa-solid fa-info fa-sm"></i>
        </div>
        <h4>Aclaración:</h4>
        <p>Los botones de arriba de los formularios cambian las funciones de los mismos. Consultar la tabla del final de la pagina para saber el id del producto o categoria que desea editar o eliminar.</p>
    </div>

    <div class="form-type">
        <input class="btns-admin" type="button" value="Editar" number="1">
        <input class="btns-admin" type="button" value="Agregar" number="2">
        <input class="btns-admin" type="button" value="Eliminar" number="3">
    </div>

    <form action="agregarProducto" method="POST" class="form" id="form-productos"> 
        <p class="form-title" id="form-title-productos">Agregar Producto</p>

        <div class="noMostrar" id="select-ids-productos">
            <label for="id">Seleccione el id de un producto</label>
            <select name="id">
                <?php foreach ($products as $product) : ?>
                    <option value="<?= $product->Product_id ?>"><?= $product->Product_id ?></option>
                <?php endforeach ?>
            </select>
        </div>

        <div class="" id="cont-form-productos">
            <div class="form-input__container">
                <label>Nombre del producto</label>
                <input name="Product_name" type="text" class="form-control">
            </div>

            <div class="form-input__container">
                <label>Mililitros</label>
                <input type="number" name="Milliliters" class="form-control" min="1" max="3000"></input>
            </div>

            <div class="form-input__container">
                <label>Precio</label>
                <input type="number" name="Price" class="form-control" min="1"></input>
            </div>

            <div class="form-select__conteiner select-width">
                <label>Categoria</label>
                <select required name="Category_id" class="form-control">
                    <?php foreach ($categorys as $category) : ?>
                        <option value="<?= $category->Category_id ?>"><?= $category->Category_name ?></option>
                    <?php endforeach ?>
                </select>
            </div>
        </div>

        <button action="administrar" type="submit" class="form-submit" id="btn-submit-productos">Enviar</button>
    </form>

    <div class="form-type">
        <input class="btns-admin" type="button" value="Editar" number="4">
        <input class="btns-admin" type="button" value="Agregar" number="5">
        <input class="btns-admin" type="button" value="Eliminar" number="6">
    </div>

    <form action="agregarCategoria" class="form" method="POST" id="form-categorias">
        <p class="form-title" id="form-title-categorias">Agregar Categoria</p>

        <div class="noMostrar" id="select-ids-categorias">
            <label for="Category_id">Seleccione una categoria</label>

            <p id="p-eliminar-producto">Recuerde que para eliminar la catogoria, esta no debe tener productos.</p>
            <select name="Category_id">
                <?php foreach ($categorys as $category) : ?>
                    <option value="<?= $category->Category_id ?>"><?= $category->Category_name ?></option>
                <?php endforeach ?>
            </select>
        </div>

        <div class="" id="cont-form-categorias">
            <div class="form-input__container">
                <label>Nombre de la categoria</label>
                <input name="Category_name" type="text" class="form-control">
            </div>
        </div>

        <button action="administrar" type="submit" class="form-submit" id="btn-submit-categorias">Enviar</button>
    </form>

    <div class="tabla-container">
        <h3>Info de los Productos</h3>
        <p>Tabla para mostrar información y eliminar productos de la base de datos</p>
        <table>
            <thead>
                <tr>
                    <th>Id</th>
                    <th>Producto</th>
                    <th>Mililitros</th>
                    <th>Precio</th>
                    <th>Categoria</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($products as $product) : ?>
                    <tr>
                        <td><?= $product->Product_id ?></td>
                        <td><?= $product->Product_name ?></td>
                        <td><?= $product->Milliliters ?>ml</td>
                        <td>$<?= $product->Price ?></td>
                        <td>
                            <?php
                            $i = 0;
                            $var = false;
                            while ($var == false && $i < count($categorys)) {
                                if ($product->Category_id == $categorys[$i]->Category_id) {
                                    $var = true;
                                    echo "(" . $categorys[$i]->Category_id . ")" . $categorys[$i]->Category_name;
                                }
                                $i++;
                            } ?>
                        </td>
                    </tr>
                <?php endforeach ?>
            </tbody>
        </table>
    </div>
</main>
<script src="js/administrar.js"></script>
<script src="js/main.js"></script>
</body>

</html>