<div class="card">
    <div class="card-img">
        <img src="./img/fernet-branca-750ml-recorted.png" alt="fernet branca 750ml">
    </div>
    <div class="card-text">
        <p class="card-title">Fernet Branca</p> <!-- Aca va el nombre del producto -->
        <p class="card-subtitle">750<span>ml</span></p> <!-- Aca van los ml de la bebida se modificaria el-->
    </div>
    <hr class="card-divider">
    <div class="card-footer">
        <p class="card-price">$ 1000</p> <!-- PRECIO -->
    </div>
</div>