<footer>
    <div class="footer-contenedor">
        <div class="footer-contenedor__logo">
            <img src="img/logo-header-2.png" alt="logo" />
        </div>
    </div>
    <ul>
        <li>
            <a href="#"><img src="img/logo-redes-sociales/facebook.png" alt="logo facebook" class="logo-red__social" /></a>
        </li>
        <li>
            <a href="#"><img src="img/logo-redes-sociales/instagram.png" alt="logo instagram" class="logo-red__social" /></a>
        </li>
    </ul>
</footer>
<script src="js/main.js"></script>
</body>

</html>