<main class="main-form__inicioSesion">
    <form class="form-inicioSesion">
        <p class="form-inicioSesion__title">Ingrese a su cuenta</p>
        <div class="form-inicioSesion__input--container">
            <input type="email" placeholder="   Email">
        </div>
        <div class="form-inicioSesion__input--container">
            <input type="password" placeholder="    Contraseña">
        </div>
        <button type="submit" class="form-inicioSesion__submit">
            Ingresar
        </button>
    </form>
</main>