<div class="cont-form__inicio--sesion">
    <form class="form-inicio__sesion">
        <p class="form-inicio__sesion--title">Ingrese a su cuenta</p>
        <div class="form-inicio__sesion--input__container">
            <input type="email" placeholder="   Email">
            <span>
            </span>
        </div>
        <div class="form-inicio__sesion--input__container">
            <input type="password" placeholder="    Contraseña">
        </div>
        <button type="submit" class="form-inicio__sesion--submit">
            Ingresar
        </button>
    </form>
</div>