<?php require 'templates/header.phtml';?>
<main class="main-form__inicioSesion">
    <form action="ingreso" method="POST" class="form-inicioSesion">
        <p class="form-inicioSesion__title">Ingrese a su cuenta</p>
        <div class="form-inicioSesion__input--container">
            <input name="email_user"  placeholder="   Email">
        </div>
        <div class="form-inicioSesion__input--container">
            <input required name="password" type="password" placeholder="    Contraseña">
        </div>
        <?php if ($error) : ?>
            <div class='alert alert-danger' role='alert'>
                <?= $error ?>
            </div> 
        <?php endif ?>

        <button type="submit" class="form-inicioSesion__submit">
            Ingresar
        </button>
        <a href="registro">No tienes una cuenta? crea una cuenta.</a>
        <a href="logout">Deslogearse.</a>
    </form>
</main>
<?php require 'templates/footer.phtml';?>

