<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>The Winery</title>
    <link rel="stylesheet" href="css/styles.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>

<body>
    <header>
        <div class="nav-header">
            <button class="btn-nav" id="btn-nav">
                <i class="fa-solid fa-bars fa-xl"></i>
            </button>
            <a href="home" class="logo-link"><img src="img/logo-header-2.png" alt="logo" /></a>
        </div>
        <nav class="nav-links" id="nav-links">
            <ul>
                <li class="nav-link"><a href="home">Inicio</a></li>
                <li class="nav-link"><a href="productos">Productos</a></li><!-- -0 -->
                <li class="nav-link"><a href="administrar">Administrar</a></li>
                <li class="nav-link none-border"><a href="inicioSesion"><i class="fa-solid fa-user fa-xl"></i></a></li>
            </ul>
        </nav>
    </header>