    <div class="container-cards">
        <?php foreach ($products as $product) : ?>
            <div class="card">
                <div class="card-img">
                    <img src="img/productos/<?= $product->Product_name ?>.png" alt="<?= $product->Product_name ?> <?= $product->Milliliters ?>ml">
                </div>
                <div class="card-info">
                    <div class="card-description">
                        <p class="card-productName"><?= $product->Product_name ?></p>
                        <p class="card-milliliters"><?= $product->Milliliters ?>ml</p>
                        
                    </div>
                    <hr class="card-divider">
                    <div class="card-footer">
                        <p class="card-price">$<?= $product->Price ?></p>
                    </div>
                    
                </div>
            </div>
        <?php endforeach ?>
    </div>

<?php require('templates/footer.phtml'); ?>