<?php require('templates/header.phtml');  ?>

<ul class="list-categorys">
    <li>
        <a href="productos-0">Todos</a>
    </li>
    <?php foreach ($categoryes as $category) :
        if ($category->Category_id) : ?>
            <li>
                <a href="productos-<?php echo $category->Category_id ?>"><?php echo $category->Category_name ?></a>
            </li>
        <?php endif ?>
    <?php endforeach ?>
</ul>